server:
  port: 8081

spring.application.name: spring-boot-keycloak

#Security Configuration for Keycloak
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/SpringSecurityKeycloakRealm
          #jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# JWT Decoder Configuration
jwt:
  auth:
    converter:
      resource-id: my-app-client
      principal-attribute: principal_username

logging:
  level:
    org.springframework.security: TRACE